version: '3'
services:
  city_1:
    build:
      context: .
    command: ["java", "City", "1", "2", "3", "4"]
    networks:
      - city_network

  city_2:
    build:
      context: .
    command: ["java", "City", "2", "1", "3", "4"]
    networks:
      - city_network

  city_3:
    build:
      context: .
    command: ["java", "City", "3", "1", "2", "4"]
    networks:
      - city_network

  city_4:
    build:
      context: .
    command: ["java", "City", "4", "1", "2", "3"]
    networks:
      - city_network

networks:
  city_network:
